/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navigation from "../components/navigation";
import { useState } from "react";
import Link from "next/link";
import Dropdown from "../components/dropdown";
import Footer from "../components/footer";
import Sponsorships from "../components/sponsorships";
import Contact from "../components/contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isOpen, setOpen] = useState(false);
  const [open, setOpenDropdown] = useState(false);

  const handleMenuOne = () => {
    console.log("Go To Ticket Link 1");
  };

  const handleMenuTwo = () => {
    console.log("Go To Ticket Link 2");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        onClick={() => {
          if (open) {
            setOpenDropdown(false);
          }
        }}
        className={`${styles.mainOther} ${isOpen && styles.overlay}`}
      >
        <Navigation
          open={open}
          setOpenDropdown={setOpenDropdown}
          isOpen={isOpen}
          setOpen={setOpen}
        />
        {isOpen && (
          <div className={styles.overlay}>
            <div className={styles.overlayContent}>
              <div className={styles.center}>
                <ul className={styles.overlayList}>
                  <li>
                    <Link href="/#charity">Charity</Link>
                  </li>
                  <li>
                    <Link href="/faq">FAQ</Link>
                  </li>
                  <li>
                    <Link href="/sponsorships">Sponsorships</Link>
                  </li>
                  <li>
                    <a href="">Merch</a>
                  </li>
                </ul>
                <div className="navigation-tickets-mobile">
                  <Dropdown
                    open={open}
                    setOpenDropdown={setOpenDropdown}
                    trigger={
                      <button>
                        Tickets{" "}
                        <span>
                          <img
                            src="/assets/chevron.png"
                            alt="navigation chevron"
                          />
                        </span>
                      </button>
                    }
                    menu={[
                      <button key={1} onClick={handleMenuOne}>
                        Event Tickets
                      </button>,
                      <button
                        key={2}
                        className="inverted"
                        onClick={handleMenuTwo}
                      >
                        PPV Tickets
                      </button>,
                    ]}
                  />
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
      <Sponsorships />
      <Contact />
      <Footer />
    </>
  );
}
